### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by lumberman** [FaisalST32/fs-scrollanimate#1]
Hello, I'm getting the next errors in the FireFox console:

- The resource from “https://cdn.jsdelivr.net/gh/FaisalST32/fs-lightbox@latest/src/css/fs-scrollanimate.min.css?ver=5.3.2” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).

- The resource from “https://cdn.jsdelivr.net/gh/FaisalST32/fs-lightbox@latest/src/js/fs-scrollanimate.min.js?ver=5.3.2” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).

**Comment by FaisalST32** [comment]
Sorry for that.

The CDN links were incorrect.

I have updated the Readme.md file with the correct ones.
